title: Phalcon Link
app:
  name: Phalcon Link
  author: 'Phalcon Team'
  description: 'URL Shortener service for https://phalcon.link'
  keywords: ''
  url: https://phalcon.link

social:
  email: team@phalconphp.com
  facebook:
  github: phalcon
  rss: phalcon
  twitter: phalconphp

meta:
  analytics: "UA-133802124-1"

include:
  - _redirects

permalink: /:title
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME



