title: Phalcon Link
description: URL Shortener service for https://phalcon.link
google_analytics: ""

permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - vendor
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME



