title: Phalcon Link
app:
  name: Phalcon Link
  author: 'Phalcon Team'
  description: 'URL Shortener service for https://phalcon.link'
  keywords: ''
  analytics: "UA-133802124-1"
  url: https://phalcon.link

url: https://phalcon.link
social:
  email: team@phalcon.io
  facebook:
  github: phalcon
  rss: phalcon
  twitter: phalconphp

include:
  - _redirects

permalink: /:title
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

# Exclude these files from your production _site
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - serve
  - updateData.php
