title: Phalcon Link
description: URL Shortener service for https://phalcon.link
analytics: "UA-133802124-1"

permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - _redirects

exclude:
  - vendor
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME



